# Generated by Django 5.1.4 on 2024-12-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('product_image', models.ImageField(upload_to='products/images/')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
