# Generated by Django 5.1.4 on 2024-12-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_order'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='inventory',
        ),
        migrations.AddField(
            model_name='sale',
            name='precio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventory.price', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
